#!/bin/sh

set -e

lb config noauto \
  --apt-recommends false \
  --apt-http-proxy "http://localhost:3142" \
  --architectures amd64 \
  --archive-areas "main contrib non-free non-free-firmware" \
  --binary-images iso-hybrid \
  --bootappend-live "calamares-settings=local boot=live components username=user locales=en_US.UTF-8" \
  --bootloader syslinux \
  --cache true \
  --cache-packages true \
  --cache-stages "bootstrap chroot rootfs" \
  --chroot-filesystem squashfs \
  --debian-installer none \
  --debian-installer-gui false \
  --distribution trixie \
  --firmware-chroot false \
  --firmware-binary false \
  --linux-flavours amd64 \
  --memtest none \
  --mirror-bootstrap "http://deb.debian.org/debian/" \
  --mirror-chroot "http://deb.debian.org/debian/" \
  --mirror-binary "http://deb.debian.org/debian/" \
  --mirror-binary-security "http://security.debian.org/debian-security/" \
  --mirror-chroot-security "http://security.debian.org/debian-security/" \
  --mode debian \
  --iso-application "Tabian OS Installation Media" \
  --iso-publisher "Tabian OS Project" \
  --iso-preparer "Tabian OS Project; https://github.com/tayebelleuch-ops/my_linux_distro.git" \
  --iso-volume "Tabian_OS_Live" \
  --checksums sha256 \
  "${@}"
