---
dontChroot: false
timeout: 100
script:
    - "mkdir -p @@ROOT@@/usr/local/bin/"
    - description: "Placing Tabian OS Post-Install Script..."
      command: "cp /usr/local/bin/setup.sh @@ROOT@@/usr/local/bin/setup.sh && chmod +x @@ROOT@@/usr/local/bin/setup.sh"
    - "systemctl set-default multi-user.target"
