---
# Rules for user creation in Tabian OS
passwordRequirements:
    minLength: 4
    maxLength: -1
    strengthRequired: 0
    libpwquality:
        required: false
defaultGroups:
    - name: "sudo"
      must_exist: false
    - name: "audio"
      must_exist: false
    - name: "video"
      must_exist: false
    - name: "disk"
      must_exist: false
    - name: "wheel"
      must_exist: false
