---
showSupportUrl:         true
showKnownIssuesUrl:     true
showReleaseNotesUrl:    true

requirements:
    requiredStorage:    15
    requiredRam:        1.0
    check:
        - storage
        - ram
        - power
	- - "<b><span style='color: #ff0000;'>!!!!NOTICE: operations (like keyboard layout selections) made during this setup will take effect ONLY after the installation finishes and the system reboots.be aware of this when typing your information(username, password...)</span></b>"
        - root
    required:
        - storage
        - ram
        - root
