---
# Master sequence layout for Tabian OS Installer
modules-search: [/usr/lib/x86_64-linux-gnu/calamares/modules, local ]

instances:
  - id:      copy_script
    module:  shellprocess
    config:  shellprocess.conf

sequence:
  - show:
    - welcome
    - locale
    - keyboard
    - partition
    - users
    - summary
  - exec:
    - partition
    - mount
    - unpackfs
    - machineid
    - fstab
    - locale
    - keyboard
    - localecfg
    - users
    - networkcfg
    - hwclock
    - services-systemd
    - bootloader
    - shellprocess@copy_script
    - umount
  - show:
    - finished

branding: default
prompt-on-desktop-error: false
rollback: false
